import React, { useState } from "react";
import {
  LayoutDashboard,
  Eye,
  BarChart3,
  FileText,
  History,
  Shield,
  Calendar,
  Download,
  CheckCircle,
  AlertTriangle,
  ChevronRight,
} from "lucide-react";

/* =======================
   Weekly & Monthly Reports – With Exact Client Sidebar
======================= */
export default function WeeklyMonthlyReports() {
  const [activeTab, setActiveTab] = useState("monthly");

  return (
    <div className="flex min-h-screen bg-white">
      {/* SIDEBAR – Identical to Client Dashboard */}
      <aside className="w-80 bg-gray-950 flex flex-col">
        <div className="p-8 border-b border-gray-800">
          <p className="text-sm text-gray-400 mt-1">Client Portal (View-Only)</p>
        </div>

        <nav className="flex-1 px-6 py-8 space-y-2">
          <SidebarItem icon={<LayoutDashboard />} label="Dashboard" />
          <SidebarItem icon={<Eye />} label="View All Observations" />
          <SidebarItem icon={<BarChart3 />} label="Graphs & Site Insights" />
          <SidebarItem icon={<FileText />} label="Weekly/Monthly Reports" active />
          <SidebarItem icon={<History />} label="Activity History" />
        </nav>
      </aside>

      {/* MAIN CONTENT */}
      <main className="flex-1 p-12 overflow-y-auto">
        {/* HEADER */}
        <div className="mb-12">
          <h1 className="text-4xl font-bold text-gray-900 mb-4 flex items-center gap-4">
            <FileText className="text-red-600" size={48} />
            Weekly & Monthly Safety Reports
          </h1>
          <p className="text-xl text-gray-600">
            View-only compliance reports generated by REDVION
          </p>
          <div className="flex items-center gap-3 mt-6 text-lg text-gray-600">
            <Calendar size={24} />
            <span>Last Generated: <strong>Today, December 20, 2025</strong></span>
          </div>
        </div>

        {/* TABS */}
        <div className="flex gap-6 mb-12 border-b border-gray-200">
          <button
            onClick={() => setActiveTab("monthly")}
            className={`pb-4 px-2 text-xl font-semibold border-b-4 transition-all duration-300 ${
              activeTab === "monthly"
                ? "border-red-600 text-red-600"
                : "border-transparent text-gray-600 hover:text-gray-900"
            }`}
          >
            Monthly Reports
          </button>
          <button
            onClick={() => setActiveTab("weekly")}
            className={`pb-4 px-2 text-xl font-semibold border-b-4 transition-all duration-300 ${
              activeTab === "weekly"
                ? "border-red-600 text-red-600"
                : "border-transparent text-gray-600 hover:text-gray-900"
            }`}
          >
            Weekly Reports
          </button>
        </div>

        {/* CONTENT */}
        <div className="space-y-12">
          {activeTab === "monthly" ? (
            <>
              <MonthlyReportCard
                period="December 2025"
                badge="Current Month"
                stats={[
                  "156 Total Observations",
                  "128 Closed • 28 Open",
                  "Resolution Rate: 82%",
                  "Safety Score: 94% ↑ 4% vs last month",
                ]}
              />

              <PreviousReportLink title="November 2025 Monthly Report" date="Nov 30, 2025" />
              <PreviousReportLink title="October 2025 Monthly Report" date="Oct 31, 2025" />
            </>
          ) : (
            <>
              <WeeklyReportCard
                period="Week 51 (Dec 14 – Dec 20, 2025)"
                badge="This Week"
                stats={[
                  "18 New Observations",
                  "15 Resolved This Week",
                  "High-Risk Items Reduced by 30%",
                  "Resolution Rate This Week: 83%",
                ]}
              />

              <PreviousReportLink title="Week 50 (Dec 7 – Dec 13, 2025)" date="Dec 13, 2025" />
              <PreviousReportLink title="Week 49 (Nov 30 – Dec 6, 2025)" date="Dec 6, 2025" />
            </>
          )}
        </div>

        {/* EXPORT SECTION */}
        <div className="mt-16 grid grid-cols-1 md:grid-cols-2 gap-8">
          <ExportButton
            label="Download PDF Report"
            desc="Professional executive summary with graphs and insights"
            color="red"
          />
          <ExportButton
            label="Export to Excel"
            desc="Complete dataset with all observations and breakdowns"
            color="green"
          />
        </div>

        {/* VIEW-ONLY NOTE */}
        <p className="text-center text-gray-500 mt-12 text-lg">
          All reports are generated and verified by your dedicated REDVION safety team.  
          This is a <strong>view-only portal</strong> for maximum transparency.
        </p>
      </main>
    </div>
  );
}

/* =======================
   Sidebar Item – White active background (exact match)
======================= */
function SidebarItem({ icon, label, active = false }) {
  return (
    <div
      className={`group flex items-center gap-5 px-6 py-5 rounded-2xl cursor-pointer transition-all duration-300 ${
        active
          ? "bg-white text-gray-900 font-bold shadow-xl"
          : "text-gray-400 hover:bg-gray-800 hover:text-white"
      }`}
    >
      <div className="p-3 rounded-xl bg-gray-800 group-hover:bg-white/10 transition-colors">
        {React.cloneElement(icon, { size: 28 })}
      </div>
      <span className="text-xl font-medium">{label}</span>
    </div>
  );
}

/* =======================
   Monthly Report Card
======================= */
function MonthlyReportCard({ period, badge, stats }) {
  return (
    <div className="bg-white rounded-3xl shadow-lg border-l-8 border-red-600 p-10">
      <div className="flex justify-between items-start mb-8">
        <div>
          <h3 className="text-3xl font-bold text-gray-900">Monthly Safety Report</h3>
          <p className="text-2xl text-gray-600 mt-3">{period}</p>
        </div>
        <span className="px-6 py-3 rounded-full text-lg font-bold bg-red-100 text-red-700">
          {badge}
        </span>
      </div>

      <div className="space-y-4 text-gray-700">
        {stats.map((stat, i) => (
          <p key={i} className="text-xl leading-relaxed">
            {stat}
          </p>
        ))}
      </div>

      <p className="text-gray-500 mt-10">Generated on December 20, 2025</p>
    </div>
  );
}

/* =======================
   Weekly Report Card
======================= */
function WeeklyReportCard({ period, badge, stats }) {
  return (
    <div className="bg-white rounded-3xl shadow-lg border-l-8 border-orange-500 p-10">
      <div className="flex justify-between items-start mb-8">
        <div>
          <h3 className="text-3xl font-bold text-gray-900">Weekly Safety Summary</h3>
          <p className="text-2xl text-gray-600 mt-3">{period}</p>
        </div>
        <span className="px-6 py-3 rounded-full text-lg font-bold bg-orange-100 text-orange-700">
          {badge}
        </span>
      </div>

      <div className="space-y-4 text-gray-700">
        {stats.map((stat, i) => (
          <p key={i} className="text-xl leading-relaxed">
            {stat}
          </p>
        ))}
      </div>

      <p className="text-gray-500 mt-10">Generated on December 20, 2025</p>
    </div>
  );
}

/* =======================
   Previous Report Link
======================= */
function PreviousReportLink({ title, date }) {
  return (
    <div className="bg-gray-50 rounded-2xl p-6 border border-gray-200 hover:shadow-md transition-shadow cursor-pointer group">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <FileText className="text-gray-600" size={32} />
          <div>
            <h4 className="text-xl font-semibold text-gray-900">{title}</h4>
            <p className="text-gray-500">Available since {date}</p>
          </div>
        </div>
        <ChevronRight className="text-gray-400 group-hover:text-red-600 group-hover:translate-x-2 transition-all" size={28} />
      </div>
    </div>
  );
}

/* =======================
   Export Button
======================= */
function ExportButton({ label, desc, color }) {
  const colors = {
    red: "from-red-500 to-red-600 hover:from-red-600 hover:to-red-700",
    green: "from-green-500 to-emerald-600 hover:from-green-600 hover:to-emerald-700",
  };

  return (
    <button
      className={`rounded-3xl p-10 bg-gradient-to-r ${colors[color]} text-white shadow-2xl transition-all duration-500 hover:scale-105 hover:shadow-3xl`}
    >
      <div className="flex flex-col items-center text-center">
        <div className="flex items-center gap-5 mb-4">
          <Download size={48} />
          <span className="text-2xl font-bold">{label}</span>
        </div>
        <p className="text-white/90 text-lg max-w-sm">{desc}</p>
      </div>
    </button>
  );
}