import React, { useState, useEffect } from "react";
import {
  FileText,
  Calendar,
  Download,
  ChevronRight,
} from "lucide-react";
import ClientSidebar from "./ClientSidebar";
import axios from "axios";

const API_BASE = "http://localhost:5001/api/client"; // your client API base

// Helper to get token
const getAuthHeader = () => {
  const token = localStorage.getItem("token");
  return { Authorization: `Bearer ${token}` };
};

export default function WeeklyMonthlyReports() {
  const [activeTab, setActiveTab] = useState("monthly");
  const [reports, setReports] = useState({ monthly: [], weekly: [] });
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  // Fetch reports from backend
  const fetchReports = async () => {
    try {
      setLoading(true);
      const res = await axios.get(`${API_BASE}/reports`, {
        headers: getAuthHeader(),
        withCredentials: true,
      });
      // Assuming backend returns { monthly: [...], weekly: [...] }
      setReports(res.data.data || { monthly: [], weekly: [] });
    } catch (err) {
      console.error("Failed to fetch reports:", err);
      setError(err.response?.data?.message || "Failed to fetch reports");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchReports();
  }, []);

  if (loading) return <div className="p-8 text-center text-xl">Loading reports...</div>;
  if (error) return <div className="p-8 text-center text-red-500">{error}</div>;

  const currentReports = activeTab === "monthly" ? reports.monthly : reports.weekly;

  return (
    <div className="flex min-h-screen bg-gray-50">
      <ClientSidebar />

      <main className="flex-1 p-12 overflow-y-auto">
        {/* HEADER */}
        <div className="mb-12 animate-fade-in">
          <h1 className="text-4xl font-bold text-gray-900 mb-4 flex items-center gap-4">
            <FileText className="text-red-600" size={48} />
            Weekly & Monthly Safety Reports
          </h1>
          <p className="text-xl text-gray-600">
            View-only compliance reports generated by REDVION
          </p>
        </div>

        {/* TABS */}
        <div className="flex gap-6 mb-12 border-b border-gray-200 animate-slide-up">
          <button
            onClick={() => setActiveTab("monthly")}
            className={`pb-4 px-2 text-xl font-semibold border-b-4 transition-all duration-300 ${
              activeTab === "monthly"
                ? "border-red-600 text-red-600"
                : "border-transparent text-gray-600 hover:text-gray-900"
            }`}
          >
            Monthly Reports
          </button>
          <button
            onClick={() => setActiveTab("weekly")}
            className={`pb-4 px-2 text-xl font-semibold border-b-4 transition-all duration-300 ${
              activeTab === "weekly"
                ? "border-red-600 text-red-600"
                : "border-transparent text-gray-600 hover:text-gray-900"
            }`}
          >
            Weekly Reports
          </button>
        </div>

        {/* REPORT CARDS */}
        <div className="space-y-12">
          {currentReports.length > 0 ? (
            currentReports.map((report, i) => (
              <ReportCard
                key={report._id || i}
                period={report.period}
                badge={report.badge || (activeTab === "monthly" ? "Current Month" : "This Week")}
                stats={report.stats || []}
                generatedAt={report.generatedAt}
                delay={100 + i * 100}
              />
            ))
          ) : (
            <p className="text-center text-gray-500 text-xl">No reports available for this period.</p>
          )}
        </div>

        {/* EXPORT BUTTONS */}
        <div className="mt-16 grid grid-cols-1 md:grid-cols-2 gap-8">
          <ExportButton
            label="Download PDF Report"
            desc="Professional executive summary with graphs and insights"
            color="red"
            onClick={() => downloadReport("pdf")}
          />
          <ExportButton
            label="Export to Excel"
            desc="Complete dataset with all observations and breakdowns"
            color="green"
            onClick={() => downloadReport("excel")}
          />
        </div>

        <p className="text-center text-gray-500 mt-12 text-lg animate-fade-in">
          All reports are generated and verified by your dedicated REDVION safety team.  
          This is a <strong>view-only portal</strong> for maximum transparency.
        </p>
      </main>

      <style jsx>{`
        @keyframes fadeIn { from { opacity: 0; transform: translateY(-10px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes slideUp { from { opacity: 0; transform: translateY(30px); } to { opacity: 1; transform: translateY(0); } }
        .animate-fade-in { animation: fadeIn 0.8s ease-out forwards; }
        .animate-slide-up { animation: slideUp 0.7s ease-out forwards; }
      `}</style>
    </div>
  );

  // Function to download report
  async function downloadReport(format = "pdf") {
    try {
      const res = await axios.get(`${API_BASE}/reports/download`, {
        headers: getAuthHeader(),
        params: { format },
        responseType: "blob",
      });
      const url = window.URL.createObjectURL(new Blob([res.data]));
      const link = document.createElement("a");
      link.href = url;
      link.setAttribute("download", `SafetyReport.${format}`);
      document.body.appendChild(link);
      link.click();
      link.remove();
    } catch (err) {
      console.error("Failed to download report:", err);
      alert("Failed to download report. Please try again.");
    }
  }
}

// Reusable Report Card
function ReportCard({ period, badge, stats, generatedAt, delay }) {
  return (
    <div className="bg-white rounded-3xl shadow-lg border-l-8 border-red-600 p-10 animate-slide-up" style={{ animationDelay: `${delay}ms` }}>
      <div className="flex justify-between items-start mb-8">
        <div>
          <h3 className="text-3xl font-bold text-gray-900">{badge} Safety Report</h3>
          <p className="text-2xl text-gray-600 mt-3">{period}</p>
        </div>
        <span className="px-6 py-3 rounded-full text-lg font-bold bg-red-100 text-red-700">{badge}</span>
      </div>
      <div className="space-y-4 text-gray-700">
        {stats.map((stat, i) => (
          <p key={i} className="text-xl leading-relaxed">{stat}</p>
        ))}
      </div>
      {generatedAt && <p className="text-gray-500 mt-10">Generated on {new Date(generatedAt).toLocaleDateString()}</p>}
    </div>
  );
}

// Reusable Export Button
function ExportButton({ label, desc, color, onClick }) {
  const colors = {
    red: "bg-red-500 hover:bg-red-600",
    green: "bg-green-500 hover:bg-green-600",
  };

  return (
    <button
      className={`rounded-xl p-6 ${colors[color]} text-white shadow-md transition-all duration-300 hover:shadow-lg hover:-translate-y-1 animate-slide-up`}
      onClick={onClick}
    >
      <div className="flex flex-col items-center text-center">
        <Download size={32} className="mb-3" />
        <span className="text-xl font-bold mb-2">{label}</span>
        <p className="text-base opacity-90">{desc}</p>
      </div>
    </button>
  );
}
